### ISSUE TITLE
1.18.2 Can't drive on Grass path blocks

### ISSUE THREAD

**Issue by ADM8** [SBDPlugins/VehiclesPlus#125] opened 2022-04-27 22:23 UTC
Vehicles that drive over grass path blocks can't drive back onto normal blocks

To reproduce:
1. Drive on grass path blocks
2. stuck
3. agony

Drive over the blocks

**Server and Plugin Information**
 - Installed plugins: everything vehicleplus needs
 - VehiclesPlus Version:  Newest
 - Server Platform and Version : newest 1.18.2 paper jar

**Comment by stijnb1234** [comment] 2022-04-28 05:47
Duplicate of #78

Those blocks have the same problem as slabs.

**Closed by stijnb1234** 2022-04-28 05:47 UTC
