### ISSUE TITLE
car does not move

### ISSUE THREAD

**Issue by poris551** [SBDPlugins/VehiclesPlus#106] opened 2021-07-19 23:18 UTC
**Describe the bug**  
all vehicles are not moving (armor stand doesn't seem to be moving)

**To Reproduce**  
1. examplecar give
2. open garage
3. spawn vehicle
4. enter driver seat
5. wasd key
6. not move

**Screenshots or Video Recordings**  
https://imgur.com/a/zJofF52
(Only the vehicle texture is covered, and the examplecar setting is the same.)

**Server and Plugin Information**
 - Installed plugins: Vault, Economy, VehiclesPlus-Pro, ProtocolLib
 - VehiclesPlus Version: 2.3.0
 - Pro or Lite? : Pro
 - Server Platform and Version : Paper 1.16.3 #253 / Paper 1.16.5 #782
 - Operating System (if applicable): Windows 10

**Comment by stijnb1234** [comment] 2021-07-20 05:21
Possible duplicate of #104

Please check answer there to make sure that setting is disabled.

**Closed** 2021-08-09 08:41 UTC
Labels: Bug
