### ISSUE TITLE
Add collision damage

### ISSUE THREAD

**Issue by NFDCPP** [SBDPlugins/VehiclesPlus#120] opened 2022-01-24 21:28 UTC
It would be nice if you added in VPRO3.0 that when a car hits a wall, or another car driving more than 40 km / h, players in this car get damage and various effects, e.g. nauseua (spinning screen

**Comment by stijnb1234** [comment] 2022-03-14 15:55
Good idea! Will check what's possible, although it will not be added in the first release of v3.

**Comment by stijnb1234** [comment] 2022-03-14 15:57
Duplicate of #118

**Closed by stijnb1234** 2022-03-14 15:57 UTC
Labels: Feature Request
